<div class="overlay" data-overlay></div>
<div class="modal" data-modal>

    <div class="modal-close-overlay" data-modal-overlay></div>

    <div class="modal-content">

      <button class="modal-close-btn" data-modal-close>
        <ion-icon name="close-outline"></ion-icon>
      </button>

      <div class="newsletter-img">
        <img src="<?php echo $block->getViewFileUrl('Dhanu_CustomModule::images/newsletter.png'); ?>" alt="subscribe newsletter" width="400" height="400">
      </div>

      <div class="newsletter">

        <form action="#">

          <div class="newsletter-header">

            <h3 class="newsletter-title">Subscribe Newsletter.</h3>

            <p class="newsletter-desc">
              Subscribe the <b>Dhanu_CustomModule</b> to get latest products and discount update.
            </p>

          </div>

          <input type="email" name="email" class="email-field" placeholder="Email Address" required>

          <button type="submit" class="btn-newsletter">Subscribe</button>

        </form>

      </div>

    </div>

  </div>

  <style type="text/css">
    <?php echo file_get_contents($block->getViewFileUrl('Dhanu_CustomModule::css/modal.css')); ?>
</style>

<script type="application/javascript" defer>
  console.log('script tag');
     <?php echo file_get_contents($block->getViewFileUrl('Dhanu_CustomModule::js/custom.js')); ?>
</script>